---
title: "Lab 3: Depth-Damage Models"
subtitle: "DataFrames and Distributions"
author: "Patricia Hashimoto"
date: 2024-01-26
week: 3
categories: [Lab]

# code to use
jupyter: julia-1.10

format: 
    html:
        theme: spacelab
        copy-code: true
        code-overflow: wrap
        toc: true
        anchor-sections: true
        callout-appearance: simple
        reference-location: document
        citations-hover: true
        code-annotations: hover
        code-line-numbers: true
        html-math-method: katex

    # YOU CAN DO PDF OR DOCX BUT NOT BOTH
    # IF YOU UNCOMMENT docx, COMMENT OR DELETE pdf
    pdf:
        documentclass: article
        fontsize: 11pt
        geometry:
            - margin=1in  
        number-sections: true
        code-line-numbers: true

    #docx: 
    #    toc: true
    #    fig-format: png
    #    number-sections: true
    #    code-line-numbers: true

date-format: "ddd., MMM. D"
---


```{julia}
using CSV
using DataFrames
using DataFramesMeta
using Distributions
using Interpolations
using Plots
using StatsPlots
using Unitful
using Random

Plots.default(; margin=6Plots.mm)
```

# Site information
I selected the water gauge at 8771450 Galveston Pier 21, TX, which is located at the coordinates 29.31, -94.626667. The building I selected is the Ocean Star Museum Gift Shop, which is located at the coordinates 29.31046, -94.7917. Based on an estimate from Google Maps, the straight line distance between these points, not accounting for elevation differences, is less than 600 feet. An estimate from the USGS National Map Viewer suggests that this building is at an elevation of approximately 1.01m, or 3.31ft.

# Depth-Damage
```{julia}
include("depthdamage.jl")
haz_fl_dept = CSV.read("data/haz_fl_dept.csv", DataFrame)
```

Because the selected structure is a museum gift shop, we will use the HAZUS row with the description "Gift Shop, contents (Inventory)". The building appears to be one story, which is an option for buildings of this class.

```{julia}
ocean_star_row = @rsubset(
    haz_fl_dept, :Description == "Gift Shop, contents (Inventory)"
)[
    1, :,
]
ocean_star_dd = DepthDamageData(ocean_star_row)
```
```{julia}
scatter(
    ocean_star_dd.depths,
    ocean_star_dd.damages;
    xlabel="Flood Depth at Building",
    ylabel="Damage (%)",
    label="$(ocean_star_dd.description) ($(ocean_star_dd.source))",
    legend=:bottomright,
    size=(700, 500),
    title = "Ocean Star Museum Gift Shop HAZUS Damage"
)
```

```{julia}
#| output: false
itp = let # <1>
    depth_ft = ustrip.(u"ft", ocean_star_dd.depths) # <2>
    damage_frac = ocean_star_dd.damages
    Interpolations.LinearInterpolation(
        depth_ft,
        damage_frac;
        extrapolation_bc=Interpolations.Flat(), # <3>
    )
end
```


```{julia}
function get_depth_damage_function(
    depth_train::Vector{<:T}, dmg_train::Vector{<:AbstractFloat}
) where {T<:Unitful.Length}

    # interpolate
    depth_ft = ustrip.(u"ft", depth_train)
    interp_fn = Interpolations.LinearInterpolation(
        depth_ft, # <1>
        dmg_train;
        extrapolation_bc=Interpolations.Flat(), # <2>
    )

    damage_fn = function (depth::T2) where {T2<:Unitful.Length}
        return interp_fn(ustrip.(u"ft", depth)) # <3>
    end
    return damage_fn # <4>
end
```

```{julia}
damage_fn = get_depth_damage_function(ocean_star_dd.depths, ocean_star_dd.damages)
```


# Expected annual damages

The following plot shows the generalized extreme value distribution that we are assuming captures flood risk at the Galveston Pier 21 Water Gauge and at the Ocean Star Museum Gift Shop. 

```{julia}
gauge_dist = GeneralizedExtremeValue(5, 1.5, 0.1)
p1 = plot(
    gauge_dist;
    label="Gauge Distribution",
    xlabel="Water Level (ft)",
    ylabel="Probability Density",
    legend=:topright,
    linewidth=2,
)

offset = 3.31 # house is 2.5 feet above gauge
building_dist = GeneralizedExtremeValue(gauge_dist.μ - offset, gauge_dist.σ, gauge_dist.ξ)

plot!(p1, building_dist; label="Gift Shop Distribution", linewidth=2)
```

I next draw 1,000,000 samples from the generalized extreme value distribution and calculate the sample mean.

```{julia}
#| output: false 
Random.seed!(123)
samp = 1u"km".* rand(building_dist, 1000000)
```

```{julia}
dmg_fn(samp) = itp(ustrip.(u"ft", samp)) # <1>
year_vec = dmg_fn.(samp) # <2>
mc_est = mean(year_vec)
```
# Discussion

The estimate of annual damages based on 1,000,000 random samples from a generalized extreme value distribution with a mean of 5ft, a standard deviation of 1.5 ft, and  error 0.1ft is `{julia} mc_est` percent. This means that if we assume that flooding at the Galveston Pier 1 Water Gauge follows this distribution, the HAZUS depth damage curve predicts that, on average, the Ocean Star Museum Gift Shop will experience flood damage to `{julia} mc_est` percent of its content, meaning its inventory in the case of a gift shop.